name: Publish Packages

on:
  push:
    branches:
      - main # Run workflow on pushes to the main branch

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes, including tags
      pull-requests: write # Allows interacting with PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/ci-setup

      - name: Build All Packages in Dependency Order
        run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version-packages
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Trigger auto-merge workflow
        uses: actions/github-script@v7.0.1
        if: steps.changesets.outputs.hasChangesets == 'false'
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'publish-package.yml',
              ref: '${{ github.head_ref }}',
              inputs: {
                "trigger-auto-merge": "true",
              }
            })
