name: Publish Packages

on:
  push:
    branches:
      - main # Run workflow on pushes to the main branch

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes, including tags
      pull-requests: write # Allows interacting with PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/ci-setup

      # Debugging Step to check .npmrc and NPM_TOKEN
      - name: Debug .npmrc and NPM_TOKEN
        run: |
          echo "npm config list"

      - name: Build All Packages in Dependency Order
        run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version-packages
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Debugging Step to check .npmrc and NPM_TOKEN
      - name: Debug .npmrc and NPM_TOKEN
        run: |
          echo "npm config list"
